spring:
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      bootstrap-servers: localhost:9092
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/ping
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true

topics:
  pg_created: pings_created
  pg_deleted: pings_removed

server:
  port: 8082
  error:
    include-message: always